import React, { Component } from "react";
import { Router, Switch, Route } from "react-router-dom";
import DashboardPage from "./components/dashboard/DashboardPage"
import LoginPage from "./components/login/LoginForm";
import SignUpPage from "./components/login/SignUpPage";
import history from './history';


import Account_IdPage from "./components/account_id/Account_IdPage"
import Account_IdAddUpdatePage from "./components/account_id/Account_IdAddUpdatePage"
import Account_StatusPage from "./components/account_status/Account_StatusPage"
import Account_StatusAddUpdatePage from "./components/account_status/Account_StatusAddUpdatePage"
import Account_TypePage from "./components/account_type/Account_TypePage"
import Account_TypeAddUpdatePage from "./components/account_type/Account_TypeAddUpdatePage"
import Account_Type_2Page from "./components/account_type_2/Account_Type_2Page"
import Account_Type_2AddUpdatePage from "./components/account_type_2/Account_Type_2AddUpdatePage"
import Add_On_ServicesPage from "./components/add_on_services/Add_On_ServicesPage"
import Add_On_ServicesAddUpdatePage from "./components/add_on_services/Add_On_ServicesAddUpdatePage"
import BookingPage from "./components/booking/BookingPage"
import BookingAddUpdatePage from "./components/booking/BookingAddUpdatePage"
import CompanyPage from "./components/company/CompanyPage"
import CompanyAddUpdatePage from "./components/company/CompanyAddUpdatePage"
import Company_DocumentPage from "./components/company_document/Company_DocumentPage"
import Company_DocumentAddUpdatePage from "./components/company_document/Company_DocumentAddUpdatePage"
import Content_MgmtPage from "./components/content_mgmt/Content_MgmtPage"
import Content_MgmtAddUpdatePage from "./components/content_mgmt/Content_MgmtAddUpdatePage"
import Document_UploadPage from "./components/document_upload/Document_UploadPage"
import Document_UploadAddUpdatePage from "./components/document_upload/Document_UploadAddUpdatePage"
import Email_MgmtPage from "./components/email_mgmt/Email_MgmtPage"
import Email_MgmtAddUpdatePage from "./components/email_mgmt/Email_MgmtAddUpdatePage"
import Health_ResultPage from "./components/health_result/Health_ResultPage"
import Health_ResultAddUpdatePage from "./components/health_result/Health_ResultAddUpdatePage"
import MedicationPage from "./components/medication/MedicationPage"
import MedicationAddUpdatePage from "./components/medication/MedicationAddUpdatePage"
import Medication_PrescriptionPage from "./components/medication_prescription/Medication_PrescriptionPage"
import Medication_PrescriptionAddUpdatePage from "./components/medication_prescription/Medication_PrescriptionAddUpdatePage"
import Menu_ItemPage from "./components/menu_item/Menu_ItemPage"
import Menu_ItemAddUpdatePage from "./components/menu_item/Menu_ItemAddUpdatePage"
import Menu_MainPage from "./components/menu_main/Menu_MainPage"
import Menu_MainAddUpdatePage from "./components/menu_main/Menu_MainAddUpdatePage"
import Menu_Main_ItemPage from "./components/menu_main_item/Menu_Main_ItemPage"
import Menu_Main_ItemAddUpdatePage from "./components/menu_main_item/Menu_Main_ItemAddUpdatePage"
import Message_BoxPage from "./components/message_box/Message_BoxPage"
import Message_BoxAddUpdatePage from "./components/message_box/Message_BoxAddUpdatePage"
import Message_DocumentPage from "./components/message_document/Message_DocumentPage"
import Message_DocumentAddUpdatePage from "./components/message_document/Message_DocumentAddUpdatePage"
import Message_InboxPage from "./components/message_inbox/Message_InboxPage"
import Message_InboxAddUpdatePage from "./components/message_inbox/Message_InboxAddUpdatePage"
import NotificationPage from "./components/notification/NotificationPage"
import NotificationAddUpdatePage from "./components/notification/NotificationAddUpdatePage"
import Notification_LogPage from "./components/notification_log/Notification_LogPage"
import Notification_LogAddUpdatePage from "./components/notification_log/Notification_LogAddUpdatePage"
import Package_Add_OnsPage from "./components/package_add_ons/Package_Add_OnsPage"
import Package_Add_OnsAddUpdatePage from "./components/package_add_ons/Package_Add_OnsAddUpdatePage"
import Package_CategoryPage from "./components/package_category/Package_CategoryPage"
import Package_CategoryAddUpdatePage from "./components/package_category/Package_CategoryAddUpdatePage"
import Package_PatientPage from "./components/package_patient/Package_PatientPage"
import Package_PatientAddUpdatePage from "./components/package_patient/Package_PatientAddUpdatePage"
import Package_Test_GroupsPage from "./components/package_test_groups/Package_Test_GroupsPage"
import Package_Test_GroupsAddUpdatePage from "./components/package_test_groups/Package_Test_GroupsAddUpdatePage"
import Package_Test_PanelsPage from "./components/package_test_panels/Package_Test_PanelsPage"
import Package_Test_PanelsAddUpdatePage from "./components/package_test_panels/Package_Test_PanelsAddUpdatePage"
import Patient_BakPage from "./components/patient_bak/Patient_BakPage"
import Patient_BakAddUpdatePage from "./components/patient_bak/Patient_BakAddUpdatePage"
import Patient_TypePage from "./components/patient_type/Patient_TypePage"
import Patient_TypeAddUpdatePage from "./components/patient_type/Patient_TypeAddUpdatePage"
import PaymentPage from "./components/payment/PaymentPage"
import PaymentAddUpdatePage from "./components/payment/PaymentAddUpdatePage"
import PersonPage from "./components/person/PersonPage"
import PersonAddUpdatePage from "./components/person/PersonAddUpdatePage"
import Person_DocumentPage from "./components/person_document/Person_DocumentPage"
import Person_DocumentAddUpdatePage from "./components/person_document/Person_DocumentAddUpdatePage"
import Person_TypePage from "./components/person_type/Person_TypePage"
import Person_TypeAddUpdatePage from "./components/person_type/Person_TypeAddUpdatePage"
import Pre_RegistrationPage from "./components/pre_registration/Pre_RegistrationPage"
import Pre_RegistrationAddUpdatePage from "./components/pre_registration/Pre_RegistrationAddUpdatePage"
import Ref_MessagePage from "./components/ref_message/Ref_MessagePage"
import Ref_MessageAddUpdatePage from "./components/ref_message/Ref_MessageAddUpdatePage"
import Ref_Payment_MethodPage from "./components/ref_payment_method/Ref_Payment_MethodPage"
import Ref_Payment_MethodAddUpdatePage from "./components/ref_payment_method/Ref_Payment_MethodAddUpdatePage"
import Ref_RelationshipPage from "./components/ref_relationship/Ref_RelationshipPage"
import Ref_RelationshipAddUpdatePage from "./components/ref_relationship/Ref_RelationshipAddUpdatePage"
import Ref_StatePage from "./components/ref_state/Ref_StatePage"
import Ref_StateAddUpdatePage from "./components/ref_state/Ref_StateAddUpdatePage"
import RegistrationPage from "./components/registration/RegistrationPage"
import RegistrationAddUpdatePage from "./components/registration/RegistrationAddUpdatePage"
import Registration_PersonPage from "./components/registration_person/Registration_PersonPage"
import Registration_PersonAddUpdatePage from "./components/registration_person/Registration_PersonAddUpdatePage"
import Screening_PackagesPage from "./components/screening_packages/Screening_PackagesPage"
import Screening_PackagesAddUpdatePage from "./components/screening_packages/Screening_PackagesAddUpdatePage"
import Six_Digit_CodePage from "./components/six_digit_code/Six_Digit_CodePage"
import Six_Digit_CodeAddUpdatePage from "./components/six_digit_code/Six_Digit_CodeAddUpdatePage"
import Sms_LogPage from "./components/sms_log/Sms_LogPage"
import Sms_LogAddUpdatePage from "./components/sms_log/Sms_LogAddUpdatePage"
import Sms_NotificationPage from "./components/sms_notification/Sms_NotificationPage"
import Sms_NotificationAddUpdatePage from "./components/sms_notification/Sms_NotificationAddUpdatePage"
import Test_GroupPage from "./components/test_group/Test_GroupPage"
import Test_GroupAddUpdatePage from "./components/test_group/Test_GroupAddUpdatePage"
import Test_Group_PanelPage from "./components/test_group_panel/Test_Group_PanelPage"
import Test_Group_PanelAddUpdatePage from "./components/test_group_panel/Test_Group_PanelAddUpdatePage"
import Test_LocationPage from "./components/test_location/Test_LocationPage"
import Test_LocationAddUpdatePage from "./components/test_location/Test_LocationAddUpdatePage"
import Test_MarkerPage from "./components/test_marker/Test_MarkerPage"
import Test_MarkerAddUpdatePage from "./components/test_marker/Test_MarkerAddUpdatePage"
import Test_PanelPage from "./components/test_panel/Test_PanelPage"
import Test_PanelAddUpdatePage from "./components/test_panel/Test_PanelAddUpdatePage"
import Test_Reference_RangePage from "./components/test_reference_range/Test_Reference_RangePage"
import Test_Reference_RangeAddUpdatePage from "./components/test_reference_range/Test_Reference_RangeAddUpdatePage"
import Test_ResultPage from "./components/test_result/Test_ResultPage"
import Test_ResultAddUpdatePage from "./components/test_result/Test_ResultAddUpdatePage"
import Transaction_LogPage from "./components/transaction_log/Transaction_LogPage"
import Transaction_LogAddUpdatePage from "./components/transaction_log/Transaction_LogAddUpdatePage"
import User_AccountPage from "./components/user_account/User_AccountPage"
import User_AccountAddUpdatePage from "./components/user_account/User_AccountAddUpdatePage"
import Account_IdPage from "./components/account_id/Account_IdPage"
import Account_IdAddUpdatePage from "./components/account_id/Account_IdAddUpdatePage"
import Account_StatusPage from "./components/account_status/Account_StatusPage"
import Account_StatusAddUpdatePage from "./components/account_status/Account_StatusAddUpdatePage"
import Account_TypePage from "./components/account_type/Account_TypePage"
import Account_TypeAddUpdatePage from "./components/account_type/Account_TypeAddUpdatePage"
import Account_Type_2Page from "./components/account_type_2/Account_Type_2Page"
import Account_Type_2AddUpdatePage from "./components/account_type_2/Account_Type_2AddUpdatePage"
import Add_On_ServicesPage from "./components/add_on_services/Add_On_ServicesPage"
import Add_On_ServicesAddUpdatePage from "./components/add_on_services/Add_On_ServicesAddUpdatePage"
import BookingPage from "./components/booking/BookingPage"
import BookingAddUpdatePage from "./components/booking/BookingAddUpdatePage"
import CompanyPage from "./components/company/CompanyPage"
import CompanyAddUpdatePage from "./components/company/CompanyAddUpdatePage"
import Company_DocumentPage from "./components/company_document/Company_DocumentPage"
import Company_DocumentAddUpdatePage from "./components/company_document/Company_DocumentAddUpdatePage"
import Content_MgmtPage from "./components/content_mgmt/Content_MgmtPage"
import Content_MgmtAddUpdatePage from "./components/content_mgmt/Content_MgmtAddUpdatePage"
import Document_UploadPage from "./components/document_upload/Document_UploadPage"
import Document_UploadAddUpdatePage from "./components/document_upload/Document_UploadAddUpdatePage"
import Email_MgmtPage from "./components/email_mgmt/Email_MgmtPage"
import Email_MgmtAddUpdatePage from "./components/email_mgmt/Email_MgmtAddUpdatePage"
import Health_ResultPage from "./components/health_result/Health_ResultPage"
import Health_ResultAddUpdatePage from "./components/health_result/Health_ResultAddUpdatePage"
import MedicationPage from "./components/medication/MedicationPage"
import MedicationAddUpdatePage from "./components/medication/MedicationAddUpdatePage"
import Medication_PrescriptionPage from "./components/medication_prescription/Medication_PrescriptionPage"
import Medication_PrescriptionAddUpdatePage from "./components/medication_prescription/Medication_PrescriptionAddUpdatePage"
import Menu_ItemPage from "./components/menu_item/Menu_ItemPage"
import Menu_ItemAddUpdatePage from "./components/menu_item/Menu_ItemAddUpdatePage"
import Menu_MainPage from "./components/menu_main/Menu_MainPage"
import Menu_MainAddUpdatePage from "./components/menu_main/Menu_MainAddUpdatePage"
import Menu_Main_ItemPage from "./components/menu_main_item/Menu_Main_ItemPage"
import Menu_Main_ItemAddUpdatePage from "./components/menu_main_item/Menu_Main_ItemAddUpdatePage"
import Message_BoxPage from "./components/message_box/Message_BoxPage"
import Message_BoxAddUpdatePage from "./components/message_box/Message_BoxAddUpdatePage"
import Message_DocumentPage from "./components/message_document/Message_DocumentPage"
import Message_DocumentAddUpdatePage from "./components/message_document/Message_DocumentAddUpdatePage"
import Message_InboxPage from "./components/message_inbox/Message_InboxPage"
import Message_InboxAddUpdatePage from "./components/message_inbox/Message_InboxAddUpdatePage"
import NotificationPage from "./components/notification/NotificationPage"
import NotificationAddUpdatePage from "./components/notification/NotificationAddUpdatePage"
import Notification_LogPage from "./components/notification_log/Notification_LogPage"
import Notification_LogAddUpdatePage from "./components/notification_log/Notification_LogAddUpdatePage"
import Package_Add_OnsPage from "./components/package_add_ons/Package_Add_OnsPage"
import Package_Add_OnsAddUpdatePage from "./components/package_add_ons/Package_Add_OnsAddUpdatePage"
import Package_CategoryPage from "./components/package_category/Package_CategoryPage"
import Package_CategoryAddUpdatePage from "./components/package_category/Package_CategoryAddUpdatePage"
import Package_PatientPage from "./components/package_patient/Package_PatientPage"
import Package_PatientAddUpdatePage from "./components/package_patient/Package_PatientAddUpdatePage"
import Package_Test_GroupsPage from "./components/package_test_groups/Package_Test_GroupsPage"
import Package_Test_GroupsAddUpdatePage from "./components/package_test_groups/Package_Test_GroupsAddUpdatePage"
import Package_Test_PanelsPage from "./components/package_test_panels/Package_Test_PanelsPage"
import Package_Test_PanelsAddUpdatePage from "./components/package_test_panels/Package_Test_PanelsAddUpdatePage"
import Patient_BakPage from "./components/patient_bak/Patient_BakPage"
import Patient_BakAddUpdatePage from "./components/patient_bak/Patient_BakAddUpdatePage"
import Patient_TypePage from "./components/patient_type/Patient_TypePage"
import Patient_TypeAddUpdatePage from "./components/patient_type/Patient_TypeAddUpdatePage"
import PaymentPage from "./components/payment/PaymentPage"
import PaymentAddUpdatePage from "./components/payment/PaymentAddUpdatePage"
import PersonPage from "./components/person/PersonPage"
import PersonAddUpdatePage from "./components/person/PersonAddUpdatePage"
import Person_DocumentPage from "./components/person_document/Person_DocumentPage"
import Person_DocumentAddUpdatePage from "./components/person_document/Person_DocumentAddUpdatePage"
import Person_TypePage from "./components/person_type/Person_TypePage"
import Person_TypeAddUpdatePage from "./components/person_type/Person_TypeAddUpdatePage"
import Pre_RegistrationPage from "./components/pre_registration/Pre_RegistrationPage"
import Pre_RegistrationAddUpdatePage from "./components/pre_registration/Pre_RegistrationAddUpdatePage"
import Ref_MessagePage from "./components/ref_message/Ref_MessagePage"
import Ref_MessageAddUpdatePage from "./components/ref_message/Ref_MessageAddUpdatePage"
import Ref_Payment_MethodPage from "./components/ref_payment_method/Ref_Payment_MethodPage"
import Ref_Payment_MethodAddUpdatePage from "./components/ref_payment_method/Ref_Payment_MethodAddUpdatePage"
import Ref_RelationshipPage from "./components/ref_relationship/Ref_RelationshipPage"
import Ref_RelationshipAddUpdatePage from "./components/ref_relationship/Ref_RelationshipAddUpdatePage"
import Ref_StatePage from "./components/ref_state/Ref_StatePage"
import Ref_StateAddUpdatePage from "./components/ref_state/Ref_StateAddUpdatePage"
import RegistrationPage from "./components/registration/RegistrationPage"
import RegistrationAddUpdatePage from "./components/registration/RegistrationAddUpdatePage"
import Registration_PersonPage from "./components/registration_person/Registration_PersonPage"
import Registration_PersonAddUpdatePage from "./components/registration_person/Registration_PersonAddUpdatePage"
import Screening_PackagesPage from "./components/screening_packages/Screening_PackagesPage"
import Screening_PackagesAddUpdatePage from "./components/screening_packages/Screening_PackagesAddUpdatePage"
import Six_Digit_CodePage from "./components/six_digit_code/Six_Digit_CodePage"
import Six_Digit_CodeAddUpdatePage from "./components/six_digit_code/Six_Digit_CodeAddUpdatePage"
import Sms_LogPage from "./components/sms_log/Sms_LogPage"
import Sms_LogAddUpdatePage from "./components/sms_log/Sms_LogAddUpdatePage"
import Sms_NotificationPage from "./components/sms_notification/Sms_NotificationPage"
import Sms_NotificationAddUpdatePage from "./components/sms_notification/Sms_NotificationAddUpdatePage"
import Test_GroupPage from "./components/test_group/Test_GroupPage"
import Test_GroupAddUpdatePage from "./components/test_group/Test_GroupAddUpdatePage"
import Test_Group_PanelPage from "./components/test_group_panel/Test_Group_PanelPage"
import Test_Group_PanelAddUpdatePage from "./components/test_group_panel/Test_Group_PanelAddUpdatePage"
import Test_LocationPage from "./components/test_location/Test_LocationPage"
import Test_LocationAddUpdatePage from "./components/test_location/Test_LocationAddUpdatePage"
import Test_MarkerPage from "./components/test_marker/Test_MarkerPage"
import Test_MarkerAddUpdatePage from "./components/test_marker/Test_MarkerAddUpdatePage"
import Test_PanelPage from "./components/test_panel/Test_PanelPage"
import Test_PanelAddUpdatePage from "./components/test_panel/Test_PanelAddUpdatePage"
import Test_Reference_RangePage from "./components/test_reference_range/Test_Reference_RangePage"
import Test_Reference_RangeAddUpdatePage from "./components/test_reference_range/Test_Reference_RangeAddUpdatePage"
import Test_ResultPage from "./components/test_result/Test_ResultPage"
import Test_ResultAddUpdatePage from "./components/test_result/Test_ResultAddUpdatePage"
import Transaction_LogPage from "./components/transaction_log/Transaction_LogPage"
import Transaction_LogAddUpdatePage from "./components/transaction_log/Transaction_LogAddUpdatePage"
import User_AccountPage from "./components/user_account/User_AccountPage"
import User_AccountAddUpdatePage from "./components/user_account/User_AccountAddUpdatePage"


export default class Routes extends Component {
    render() {
        return (
            <Router history={history}>
                <Switch>
                <Route path="/" exact component={LoginPage}/>
                <Route path="/signup" exact component={SignUpPage}/>
                <Route path="/dashboard" exact component={DashboardPage}/>
                <Route path="/account_id" exact component={Account_IdPage}/>
<Route path="/account_id/add" exact component={Account_IdAddUpdatePage}/>
<Route path="/account_id/update/:id" exact component={Account_IdAddUpdatePage}/>
<Route path="/account_status" exact component={Account_StatusPage}/>
<Route path="/account_status/add" exact component={Account_StatusAddUpdatePage}/>
<Route path="/account_status/update/:id" exact component={Account_StatusAddUpdatePage}/>
<Route path="/account_type" exact component={Account_TypePage}/>
<Route path="/account_type/add" exact component={Account_TypeAddUpdatePage}/>
<Route path="/account_type/update/:id" exact component={Account_TypeAddUpdatePage}/>
<Route path="/account_type_2" exact component={Account_Type_2Page}/>
<Route path="/account_type_2/add" exact component={Account_Type_2AddUpdatePage}/>
<Route path="/account_type_2/update/:id" exact component={Account_Type_2AddUpdatePage}/>
<Route path="/add_on_services" exact component={Add_On_ServicesPage}/>
<Route path="/add_on_services/add" exact component={Add_On_ServicesAddUpdatePage}/>
<Route path="/add_on_services/update/:id" exact component={Add_On_ServicesAddUpdatePage}/>
<Route path="/booking" exact component={BookingPage}/>
<Route path="/booking/add" exact component={BookingAddUpdatePage}/>
<Route path="/booking/update/:id" exact component={BookingAddUpdatePage}/>
<Route path="/company" exact component={CompanyPage}/>
<Route path="/company/add" exact component={CompanyAddUpdatePage}/>
<Route path="/company/update/:id" exact component={CompanyAddUpdatePage}/>
<Route path="/company_document" exact component={Company_DocumentPage}/>
<Route path="/company_document/add" exact component={Company_DocumentAddUpdatePage}/>
<Route path="/company_document/update/:id" exact component={Company_DocumentAddUpdatePage}/>
<Route path="/content_mgmt" exact component={Content_MgmtPage}/>
<Route path="/content_mgmt/add" exact component={Content_MgmtAddUpdatePage}/>
<Route path="/content_mgmt/update/:id" exact component={Content_MgmtAddUpdatePage}/>
<Route path="/document_upload" exact component={Document_UploadPage}/>
<Route path="/document_upload/add" exact component={Document_UploadAddUpdatePage}/>
<Route path="/document_upload/update/:id" exact component={Document_UploadAddUpdatePage}/>
<Route path="/email_mgmt" exact component={Email_MgmtPage}/>
<Route path="/email_mgmt/add" exact component={Email_MgmtAddUpdatePage}/>
<Route path="/email_mgmt/update/:id" exact component={Email_MgmtAddUpdatePage}/>
<Route path="/health_result" exact component={Health_ResultPage}/>
<Route path="/health_result/add" exact component={Health_ResultAddUpdatePage}/>
<Route path="/health_result/update/:id" exact component={Health_ResultAddUpdatePage}/>
<Route path="/medication" exact component={MedicationPage}/>
<Route path="/medication/add" exact component={MedicationAddUpdatePage}/>
<Route path="/medication/update/:id" exact component={MedicationAddUpdatePage}/>
<Route path="/medication_prescription" exact component={Medication_PrescriptionPage}/>
<Route path="/medication_prescription/add" exact component={Medication_PrescriptionAddUpdatePage}/>
<Route path="/medication_prescription/update/:id" exact component={Medication_PrescriptionAddUpdatePage}/>
<Route path="/menu_item" exact component={Menu_ItemPage}/>
<Route path="/menu_item/add" exact component={Menu_ItemAddUpdatePage}/>
<Route path="/menu_item/update/:id" exact component={Menu_ItemAddUpdatePage}/>
<Route path="/menu_main" exact component={Menu_MainPage}/>
<Route path="/menu_main/add" exact component={Menu_MainAddUpdatePage}/>
<Route path="/menu_main/update/:id" exact component={Menu_MainAddUpdatePage}/>
<Route path="/menu_main_item" exact component={Menu_Main_ItemPage}/>
<Route path="/menu_main_item/add" exact component={Menu_Main_ItemAddUpdatePage}/>
<Route path="/menu_main_item/update/:id" exact component={Menu_Main_ItemAddUpdatePage}/>
<Route path="/message_box" exact component={Message_BoxPage}/>
<Route path="/message_box/add" exact component={Message_BoxAddUpdatePage}/>
<Route path="/message_box/update/:id" exact component={Message_BoxAddUpdatePage}/>
<Route path="/message_document" exact component={Message_DocumentPage}/>
<Route path="/message_document/add" exact component={Message_DocumentAddUpdatePage}/>
<Route path="/message_document/update/:id" exact component={Message_DocumentAddUpdatePage}/>
<Route path="/message_inbox" exact component={Message_InboxPage}/>
<Route path="/message_inbox/add" exact component={Message_InboxAddUpdatePage}/>
<Route path="/message_inbox/update/:id" exact component={Message_InboxAddUpdatePage}/>
<Route path="/notification" exact component={NotificationPage}/>
<Route path="/notification/add" exact component={NotificationAddUpdatePage}/>
<Route path="/notification/update/:id" exact component={NotificationAddUpdatePage}/>
<Route path="/notification_log" exact component={Notification_LogPage}/>
<Route path="/notification_log/add" exact component={Notification_LogAddUpdatePage}/>
<Route path="/notification_log/update/:id" exact component={Notification_LogAddUpdatePage}/>
<Route path="/package_add_ons" exact component={Package_Add_OnsPage}/>
<Route path="/package_add_ons/add" exact component={Package_Add_OnsAddUpdatePage}/>
<Route path="/package_add_ons/update/:id" exact component={Package_Add_OnsAddUpdatePage}/>
<Route path="/package_category" exact component={Package_CategoryPage}/>
<Route path="/package_category/add" exact component={Package_CategoryAddUpdatePage}/>
<Route path="/package_category/update/:id" exact component={Package_CategoryAddUpdatePage}/>
<Route path="/package_patient" exact component={Package_PatientPage}/>
<Route path="/package_patient/add" exact component={Package_PatientAddUpdatePage}/>
<Route path="/package_patient/update/:id" exact component={Package_PatientAddUpdatePage}/>
<Route path="/package_test_groups" exact component={Package_Test_GroupsPage}/>
<Route path="/package_test_groups/add" exact component={Package_Test_GroupsAddUpdatePage}/>
<Route path="/package_test_groups/update/:id" exact component={Package_Test_GroupsAddUpdatePage}/>
<Route path="/package_test_panels" exact component={Package_Test_PanelsPage}/>
<Route path="/package_test_panels/add" exact component={Package_Test_PanelsAddUpdatePage}/>
<Route path="/package_test_panels/update/:id" exact component={Package_Test_PanelsAddUpdatePage}/>
<Route path="/patient_bak" exact component={Patient_BakPage}/>
<Route path="/patient_bak/add" exact component={Patient_BakAddUpdatePage}/>
<Route path="/patient_bak/update/:id" exact component={Patient_BakAddUpdatePage}/>
<Route path="/patient_type" exact component={Patient_TypePage}/>
<Route path="/patient_type/add" exact component={Patient_TypeAddUpdatePage}/>
<Route path="/patient_type/update/:id" exact component={Patient_TypeAddUpdatePage}/>
<Route path="/payment" exact component={PaymentPage}/>
<Route path="/payment/add" exact component={PaymentAddUpdatePage}/>
<Route path="/payment/update/:id" exact component={PaymentAddUpdatePage}/>
<Route path="/person" exact component={PersonPage}/>
<Route path="/person/add" exact component={PersonAddUpdatePage}/>
<Route path="/person/update/:id" exact component={PersonAddUpdatePage}/>
<Route path="/person_document" exact component={Person_DocumentPage}/>
<Route path="/person_document/add" exact component={Person_DocumentAddUpdatePage}/>
<Route path="/person_document/update/:id" exact component={Person_DocumentAddUpdatePage}/>
<Route path="/person_type" exact component={Person_TypePage}/>
<Route path="/person_type/add" exact component={Person_TypeAddUpdatePage}/>
<Route path="/person_type/update/:id" exact component={Person_TypeAddUpdatePage}/>
<Route path="/pre_registration" exact component={Pre_RegistrationPage}/>
<Route path="/pre_registration/add" exact component={Pre_RegistrationAddUpdatePage}/>
<Route path="/pre_registration/update/:id" exact component={Pre_RegistrationAddUpdatePage}/>
<Route path="/ref_message" exact component={Ref_MessagePage}/>
<Route path="/ref_message/add" exact component={Ref_MessageAddUpdatePage}/>
<Route path="/ref_message/update/:id" exact component={Ref_MessageAddUpdatePage}/>
<Route path="/ref_payment_method" exact component={Ref_Payment_MethodPage}/>
<Route path="/ref_payment_method/add" exact component={Ref_Payment_MethodAddUpdatePage}/>
<Route path="/ref_payment_method/update/:id" exact component={Ref_Payment_MethodAddUpdatePage}/>
<Route path="/ref_relationship" exact component={Ref_RelationshipPage}/>
<Route path="/ref_relationship/add" exact component={Ref_RelationshipAddUpdatePage}/>
<Route path="/ref_relationship/update/:id" exact component={Ref_RelationshipAddUpdatePage}/>
<Route path="/ref_state" exact component={Ref_StatePage}/>
<Route path="/ref_state/add" exact component={Ref_StateAddUpdatePage}/>
<Route path="/ref_state/update/:id" exact component={Ref_StateAddUpdatePage}/>
<Route path="/registration" exact component={RegistrationPage}/>
<Route path="/registration/add" exact component={RegistrationAddUpdatePage}/>
<Route path="/registration/update/:id" exact component={RegistrationAddUpdatePage}/>
<Route path="/registration_person" exact component={Registration_PersonPage}/>
<Route path="/registration_person/add" exact component={Registration_PersonAddUpdatePage}/>
<Route path="/registration_person/update/:id" exact component={Registration_PersonAddUpdatePage}/>
<Route path="/screening_packages" exact component={Screening_PackagesPage}/>
<Route path="/screening_packages/add" exact component={Screening_PackagesAddUpdatePage}/>
<Route path="/screening_packages/update/:id" exact component={Screening_PackagesAddUpdatePage}/>
<Route path="/six_digit_code" exact component={Six_Digit_CodePage}/>
<Route path="/six_digit_code/add" exact component={Six_Digit_CodeAddUpdatePage}/>
<Route path="/six_digit_code/update/:id" exact component={Six_Digit_CodeAddUpdatePage}/>
<Route path="/sms_log" exact component={Sms_LogPage}/>
<Route path="/sms_log/add" exact component={Sms_LogAddUpdatePage}/>
<Route path="/sms_log/update/:id" exact component={Sms_LogAddUpdatePage}/>
<Route path="/sms_notification" exact component={Sms_NotificationPage}/>
<Route path="/sms_notification/add" exact component={Sms_NotificationAddUpdatePage}/>
<Route path="/sms_notification/update/:id" exact component={Sms_NotificationAddUpdatePage}/>
<Route path="/test_group" exact component={Test_GroupPage}/>
<Route path="/test_group/add" exact component={Test_GroupAddUpdatePage}/>
<Route path="/test_group/update/:id" exact component={Test_GroupAddUpdatePage}/>
<Route path="/test_group_panel" exact component={Test_Group_PanelPage}/>
<Route path="/test_group_panel/add" exact component={Test_Group_PanelAddUpdatePage}/>
<Route path="/test_group_panel/update/:id" exact component={Test_Group_PanelAddUpdatePage}/>
<Route path="/test_location" exact component={Test_LocationPage}/>
<Route path="/test_location/add" exact component={Test_LocationAddUpdatePage}/>
<Route path="/test_location/update/:id" exact component={Test_LocationAddUpdatePage}/>
<Route path="/test_marker" exact component={Test_MarkerPage}/>
<Route path="/test_marker/add" exact component={Test_MarkerAddUpdatePage}/>
<Route path="/test_marker/update/:id" exact component={Test_MarkerAddUpdatePage}/>
<Route path="/test_panel" exact component={Test_PanelPage}/>
<Route path="/test_panel/add" exact component={Test_PanelAddUpdatePage}/>
<Route path="/test_panel/update/:id" exact component={Test_PanelAddUpdatePage}/>
<Route path="/test_reference_range" exact component={Test_Reference_RangePage}/>
<Route path="/test_reference_range/add" exact component={Test_Reference_RangeAddUpdatePage}/>
<Route path="/test_reference_range/update/:id" exact component={Test_Reference_RangeAddUpdatePage}/>
<Route path="/test_result" exact component={Test_ResultPage}/>
<Route path="/test_result/add" exact component={Test_ResultAddUpdatePage}/>
<Route path="/test_result/update/:id" exact component={Test_ResultAddUpdatePage}/>
<Route path="/transaction_log" exact component={Transaction_LogPage}/>
<Route path="/transaction_log/add" exact component={Transaction_LogAddUpdatePage}/>
<Route path="/transaction_log/update/:id" exact component={Transaction_LogAddUpdatePage}/>
<Route path="/user_account" exact component={User_AccountPage}/>
<Route path="/user_account/add" exact component={User_AccountAddUpdatePage}/>
<Route path="/user_account/update/:id" exact component={User_AccountAddUpdatePage}/>
<Route path="/account_id" exact component={Account_IdPage}/>
<Route path="/account_id/add" exact component={Account_IdAddUpdatePage}/>
<Route path="/account_id/update/:id" exact component={Account_IdAddUpdatePage}/>
<Route path="/account_status" exact component={Account_StatusPage}/>
<Route path="/account_status/add" exact component={Account_StatusAddUpdatePage}/>
<Route path="/account_status/update/:id" exact component={Account_StatusAddUpdatePage}/>
<Route path="/account_type" exact component={Account_TypePage}/>
<Route path="/account_type/add" exact component={Account_TypeAddUpdatePage}/>
<Route path="/account_type/update/:id" exact component={Account_TypeAddUpdatePage}/>
<Route path="/account_type_2" exact component={Account_Type_2Page}/>
<Route path="/account_type_2/add" exact component={Account_Type_2AddUpdatePage}/>
<Route path="/account_type_2/update/:id" exact component={Account_Type_2AddUpdatePage}/>
<Route path="/add_on_services" exact component={Add_On_ServicesPage}/>
<Route path="/add_on_services/add" exact component={Add_On_ServicesAddUpdatePage}/>
<Route path="/add_on_services/update/:id" exact component={Add_On_ServicesAddUpdatePage}/>
<Route path="/booking" exact component={BookingPage}/>
<Route path="/booking/add" exact component={BookingAddUpdatePage}/>
<Route path="/booking/update/:id" exact component={BookingAddUpdatePage}/>
<Route path="/company" exact component={CompanyPage}/>
<Route path="/company/add" exact component={CompanyAddUpdatePage}/>
<Route path="/company/update/:id" exact component={CompanyAddUpdatePage}/>
<Route path="/company_document" exact component={Company_DocumentPage}/>
<Route path="/company_document/add" exact component={Company_DocumentAddUpdatePage}/>
<Route path="/company_document/update/:id" exact component={Company_DocumentAddUpdatePage}/>
<Route path="/content_mgmt" exact component={Content_MgmtPage}/>
<Route path="/content_mgmt/add" exact component={Content_MgmtAddUpdatePage}/>
<Route path="/content_mgmt/update/:id" exact component={Content_MgmtAddUpdatePage}/>
<Route path="/document_upload" exact component={Document_UploadPage}/>
<Route path="/document_upload/add" exact component={Document_UploadAddUpdatePage}/>
<Route path="/document_upload/update/:id" exact component={Document_UploadAddUpdatePage}/>
<Route path="/email_mgmt" exact component={Email_MgmtPage}/>
<Route path="/email_mgmt/add" exact component={Email_MgmtAddUpdatePage}/>
<Route path="/email_mgmt/update/:id" exact component={Email_MgmtAddUpdatePage}/>
<Route path="/health_result" exact component={Health_ResultPage}/>
<Route path="/health_result/add" exact component={Health_ResultAddUpdatePage}/>
<Route path="/health_result/update/:id" exact component={Health_ResultAddUpdatePage}/>
<Route path="/medication" exact component={MedicationPage}/>
<Route path="/medication/add" exact component={MedicationAddUpdatePage}/>
<Route path="/medication/update/:id" exact component={MedicationAddUpdatePage}/>
<Route path="/medication_prescription" exact component={Medication_PrescriptionPage}/>
<Route path="/medication_prescription/add" exact component={Medication_PrescriptionAddUpdatePage}/>
<Route path="/medication_prescription/update/:id" exact component={Medication_PrescriptionAddUpdatePage}/>
<Route path="/menu_item" exact component={Menu_ItemPage}/>
<Route path="/menu_item/add" exact component={Menu_ItemAddUpdatePage}/>
<Route path="/menu_item/update/:id" exact component={Menu_ItemAddUpdatePage}/>
<Route path="/menu_main" exact component={Menu_MainPage}/>
<Route path="/menu_main/add" exact component={Menu_MainAddUpdatePage}/>
<Route path="/menu_main/update/:id" exact component={Menu_MainAddUpdatePage}/>
<Route path="/menu_main_item" exact component={Menu_Main_ItemPage}/>
<Route path="/menu_main_item/add" exact component={Menu_Main_ItemAddUpdatePage}/>
<Route path="/menu_main_item/update/:id" exact component={Menu_Main_ItemAddUpdatePage}/>
<Route path="/message_box" exact component={Message_BoxPage}/>
<Route path="/message_box/add" exact component={Message_BoxAddUpdatePage}/>
<Route path="/message_box/update/:id" exact component={Message_BoxAddUpdatePage}/>
<Route path="/message_document" exact component={Message_DocumentPage}/>
<Route path="/message_document/add" exact component={Message_DocumentAddUpdatePage}/>
<Route path="/message_document/update/:id" exact component={Message_DocumentAddUpdatePage}/>
<Route path="/message_inbox" exact component={Message_InboxPage}/>
<Route path="/message_inbox/add" exact component={Message_InboxAddUpdatePage}/>
<Route path="/message_inbox/update/:id" exact component={Message_InboxAddUpdatePage}/>
<Route path="/notification" exact component={NotificationPage}/>
<Route path="/notification/add" exact component={NotificationAddUpdatePage}/>
<Route path="/notification/update/:id" exact component={NotificationAddUpdatePage}/>
<Route path="/notification_log" exact component={Notification_LogPage}/>
<Route path="/notification_log/add" exact component={Notification_LogAddUpdatePage}/>
<Route path="/notification_log/update/:id" exact component={Notification_LogAddUpdatePage}/>
<Route path="/package_add_ons" exact component={Package_Add_OnsPage}/>
<Route path="/package_add_ons/add" exact component={Package_Add_OnsAddUpdatePage}/>
<Route path="/package_add_ons/update/:id" exact component={Package_Add_OnsAddUpdatePage}/>
<Route path="/package_category" exact component={Package_CategoryPage}/>
<Route path="/package_category/add" exact component={Package_CategoryAddUpdatePage}/>
<Route path="/package_category/update/:id" exact component={Package_CategoryAddUpdatePage}/>
<Route path="/package_patient" exact component={Package_PatientPage}/>
<Route path="/package_patient/add" exact component={Package_PatientAddUpdatePage}/>
<Route path="/package_patient/update/:id" exact component={Package_PatientAddUpdatePage}/>
<Route path="/package_test_groups" exact component={Package_Test_GroupsPage}/>
<Route path="/package_test_groups/add" exact component={Package_Test_GroupsAddUpdatePage}/>
<Route path="/package_test_groups/update/:id" exact component={Package_Test_GroupsAddUpdatePage}/>
<Route path="/package_test_panels" exact component={Package_Test_PanelsPage}/>
<Route path="/package_test_panels/add" exact component={Package_Test_PanelsAddUpdatePage}/>
<Route path="/package_test_panels/update/:id" exact component={Package_Test_PanelsAddUpdatePage}/>
<Route path="/patient_bak" exact component={Patient_BakPage}/>
<Route path="/patient_bak/add" exact component={Patient_BakAddUpdatePage}/>
<Route path="/patient_bak/update/:id" exact component={Patient_BakAddUpdatePage}/>
<Route path="/patient_type" exact component={Patient_TypePage}/>
<Route path="/patient_type/add" exact component={Patient_TypeAddUpdatePage}/>
<Route path="/patient_type/update/:id" exact component={Patient_TypeAddUpdatePage}/>
<Route path="/payment" exact component={PaymentPage}/>
<Route path="/payment/add" exact component={PaymentAddUpdatePage}/>
<Route path="/payment/update/:id" exact component={PaymentAddUpdatePage}/>
<Route path="/person" exact component={PersonPage}/>
<Route path="/person/add" exact component={PersonAddUpdatePage}/>
<Route path="/person/update/:id" exact component={PersonAddUpdatePage}/>
<Route path="/person_document" exact component={Person_DocumentPage}/>
<Route path="/person_document/add" exact component={Person_DocumentAddUpdatePage}/>
<Route path="/person_document/update/:id" exact component={Person_DocumentAddUpdatePage}/>
<Route path="/person_type" exact component={Person_TypePage}/>
<Route path="/person_type/add" exact component={Person_TypeAddUpdatePage}/>
<Route path="/person_type/update/:id" exact component={Person_TypeAddUpdatePage}/>
<Route path="/pre_registration" exact component={Pre_RegistrationPage}/>
<Route path="/pre_registration/add" exact component={Pre_RegistrationAddUpdatePage}/>
<Route path="/pre_registration/update/:id" exact component={Pre_RegistrationAddUpdatePage}/>
<Route path="/ref_message" exact component={Ref_MessagePage}/>
<Route path="/ref_message/add" exact component={Ref_MessageAddUpdatePage}/>
<Route path="/ref_message/update/:id" exact component={Ref_MessageAddUpdatePage}/>
<Route path="/ref_payment_method" exact component={Ref_Payment_MethodPage}/>
<Route path="/ref_payment_method/add" exact component={Ref_Payment_MethodAddUpdatePage}/>
<Route path="/ref_payment_method/update/:id" exact component={Ref_Payment_MethodAddUpdatePage}/>
<Route path="/ref_relationship" exact component={Ref_RelationshipPage}/>
<Route path="/ref_relationship/add" exact component={Ref_RelationshipAddUpdatePage}/>
<Route path="/ref_relationship/update/:id" exact component={Ref_RelationshipAddUpdatePage}/>
<Route path="/ref_state" exact component={Ref_StatePage}/>
<Route path="/ref_state/add" exact component={Ref_StateAddUpdatePage}/>
<Route path="/ref_state/update/:id" exact component={Ref_StateAddUpdatePage}/>
<Route path="/registration" exact component={RegistrationPage}/>
<Route path="/registration/add" exact component={RegistrationAddUpdatePage}/>
<Route path="/registration/update/:id" exact component={RegistrationAddUpdatePage}/>
<Route path="/registration_person" exact component={Registration_PersonPage}/>
<Route path="/registration_person/add" exact component={Registration_PersonAddUpdatePage}/>
<Route path="/registration_person/update/:id" exact component={Registration_PersonAddUpdatePage}/>
<Route path="/screening_packages" exact component={Screening_PackagesPage}/>
<Route path="/screening_packages/add" exact component={Screening_PackagesAddUpdatePage}/>
<Route path="/screening_packages/update/:id" exact component={Screening_PackagesAddUpdatePage}/>
<Route path="/six_digit_code" exact component={Six_Digit_CodePage}/>
<Route path="/six_digit_code/add" exact component={Six_Digit_CodeAddUpdatePage}/>
<Route path="/six_digit_code/update/:id" exact component={Six_Digit_CodeAddUpdatePage}/>
<Route path="/sms_log" exact component={Sms_LogPage}/>
<Route path="/sms_log/add" exact component={Sms_LogAddUpdatePage}/>
<Route path="/sms_log/update/:id" exact component={Sms_LogAddUpdatePage}/>
<Route path="/sms_notification" exact component={Sms_NotificationPage}/>
<Route path="/sms_notification/add" exact component={Sms_NotificationAddUpdatePage}/>
<Route path="/sms_notification/update/:id" exact component={Sms_NotificationAddUpdatePage}/>
<Route path="/test_group" exact component={Test_GroupPage}/>
<Route path="/test_group/add" exact component={Test_GroupAddUpdatePage}/>
<Route path="/test_group/update/:id" exact component={Test_GroupAddUpdatePage}/>
<Route path="/test_group_panel" exact component={Test_Group_PanelPage}/>
<Route path="/test_group_panel/add" exact component={Test_Group_PanelAddUpdatePage}/>
<Route path="/test_group_panel/update/:id" exact component={Test_Group_PanelAddUpdatePage}/>
<Route path="/test_location" exact component={Test_LocationPage}/>
<Route path="/test_location/add" exact component={Test_LocationAddUpdatePage}/>
<Route path="/test_location/update/:id" exact component={Test_LocationAddUpdatePage}/>
<Route path="/test_marker" exact component={Test_MarkerPage}/>
<Route path="/test_marker/add" exact component={Test_MarkerAddUpdatePage}/>
<Route path="/test_marker/update/:id" exact component={Test_MarkerAddUpdatePage}/>
<Route path="/test_panel" exact component={Test_PanelPage}/>
<Route path="/test_panel/add" exact component={Test_PanelAddUpdatePage}/>
<Route path="/test_panel/update/:id" exact component={Test_PanelAddUpdatePage}/>
<Route path="/test_reference_range" exact component={Test_Reference_RangePage}/>
<Route path="/test_reference_range/add" exact component={Test_Reference_RangeAddUpdatePage}/>
<Route path="/test_reference_range/update/:id" exact component={Test_Reference_RangeAddUpdatePage}/>
<Route path="/test_result" exact component={Test_ResultPage}/>
<Route path="/test_result/add" exact component={Test_ResultAddUpdatePage}/>
<Route path="/test_result/update/:id" exact component={Test_ResultAddUpdatePage}/>
<Route path="/transaction_log" exact component={Transaction_LogPage}/>
<Route path="/transaction_log/add" exact component={Transaction_LogAddUpdatePage}/>
<Route path="/transaction_log/update/:id" exact component={Transaction_LogAddUpdatePage}/>
<Route path="/user_account" exact component={User_AccountPage}/>
<Route path="/user_account/add" exact component={User_AccountAddUpdatePage}/>
<Route path="/user_account/update/:id" exact component={User_AccountAddUpdatePage}/>

                </Switch>
            </Router>
        )
    }
}
