<html>
<head>
<title>MyHealthcard_REST_API REST API</title>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
</head>
<body>
<div class="well">
<h1>MyHealthcard_REST_API REST API</h1>
</div>
<div class="container">
<div class="row">

<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Account_Id</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/account_id/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/account_id/read_one.php?id=1</td></tr><tr><td>Create</td><td>POST</td><td>/account_id/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/account_id/update.php</td></tr><tr><td>Delete</td><td>POST</td><td>/account_id/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Account_Status</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/account_status/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/account_status/read_one.php?id=1</td></tr><tr><td>Create</td><td>POST</td><td>/account_status/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/account_status/update.php</td></tr><tr><td>Delete</td><td>POST</td><td>/account_status/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Account_Type</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/account_type/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/account_type/read_one.php?id=1</td></tr><tr><td>Create</td><td>POST</td><td>/account_type/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/account_type/update.php</td></tr><tr><td>Delete</td><td>POST</td><td>/account_type/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Account_Type_2</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/account_type_2/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/account_type_2/read_one.php?id=1</td></tr><tr><td>Create</td><td>POST</td><td>/account_type_2/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/account_type_2/update.php</td></tr><tr><td>Delete</td><td>POST</td><td>/account_type_2/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Add_On_Services</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/add_on_services/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/add_on_services/read_one.php?id=1</td></tr><tr><td>Create</td><td>POST</td><td>/add_on_services/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/add_on_services/update.php</td></tr><tr><td>Delete</td><td>POST</td><td>/add_on_services/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Booking</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/booking/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/booking/read_one.php?id=1</td></tr><tr><td>Create</td><td>POST</td><td>/booking/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/booking/update.php</td></tr><tr><td>Delete</td><td>POST</td><td>/booking/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Company</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/company/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/company/read_one.php?id=1</td></tr><tr><td>Create</td><td>POST</td><td>/company/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/company/update.php</td></tr><tr><td>Delete</td><td>POST</td><td>/company/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Company_Document</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/company_document/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/company_document/read_one.php?id=1</td></tr><tr><td>Create</td><td>POST</td><td>/company_document/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/company_document/update.php</td></tr><tr><td>Delete</td><td>POST</td><td>/company_document/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Content_Mgmt</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/content_mgmt/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/content_mgmt/read_one.php?id=1</td></tr><tr><td>Create</td><td>POST</td><td>/content_mgmt/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/content_mgmt/update.php</td></tr><tr><td>Delete</td><td>POST</td><td>/content_mgmt/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Document_Upload</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/document_upload/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/document_upload/read_one.php?id=1</td></tr><tr><td>Create</td><td>POST</td><td>/document_upload/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/document_upload/update.php</td></tr><tr><td>Delete</td><td>POST</td><td>/document_upload/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Email_Mgmt</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/email_mgmt/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/email_mgmt/read_one.php?id=1</td></tr><tr><td>Create</td><td>POST</td><td>/email_mgmt/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/email_mgmt/update.php</td></tr><tr><td>Delete</td><td>POST</td><td>/email_mgmt/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Health_Result</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/health_result/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/health_result/read_one.php?id=1</td></tr><tr><td>Create</td><td>POST</td><td>/health_result/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/health_result/update.php</td></tr><tr><td>Delete</td><td>POST</td><td>/health_result/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Medication</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/medication/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/medication/read_one.php?id=1</td></tr><tr><td>Create</td><td>POST</td><td>/medication/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/medication/update.php</td></tr><tr><td>Delete</td><td>POST</td><td>/medication/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Medication_Prescription</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/medication_prescription/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/medication_prescription/read_one.php?id=1</td></tr><tr><td>Create</td><td>POST</td><td>/medication_prescription/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/medication_prescription/update.php</td></tr><tr><td>Delete</td><td>POST</td><td>/medication_prescription/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Menu_Item</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/menu_item/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/menu_item/read_one.php?id=1</td></tr><tr><td>Create</td><td>POST</td><td>/menu_item/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/menu_item/update.php</td></tr><tr><td>Delete</td><td>POST</td><td>/menu_item/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Menu_Main</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/menu_main/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/menu_main/read_one.php?id=1</td></tr><tr><td>Create</td><td>POST</td><td>/menu_main/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/menu_main/update.php</td></tr><tr><td>Delete</td><td>POST</td><td>/menu_main/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Menu_Main_Item</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/menu_main_item/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/menu_main_item/read_one.php?id=1</td></tr><tr><td>Create</td><td>POST</td><td>/menu_main_item/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/menu_main_item/update.php</td></tr><tr><td>Delete</td><td>POST</td><td>/menu_main_item/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Message_Box</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/message_box/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/message_box/read_one.php?id=1</td></tr><tr><td>Create</td><td>POST</td><td>/message_box/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/message_box/update.php</td></tr><tr><td>Delete</td><td>POST</td><td>/message_box/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Message_Document</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/message_document/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/message_document/read_one.php?id=1</td></tr><tr><td>Create</td><td>POST</td><td>/message_document/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/message_document/update.php</td></tr><tr><td>Delete</td><td>POST</td><td>/message_document/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Message_Inbox</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/message_inbox/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/message_inbox/read_one.php?id=1</td></tr><tr><td>Create</td><td>POST</td><td>/message_inbox/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/message_inbox/update.php</td></tr><tr><td>Delete</td><td>POST</td><td>/message_inbox/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Notification</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/notification/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/notification/read_one.php?id=1</td></tr><tr><td>Create</td><td>POST</td><td>/notification/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/notification/update.php</td></tr><tr><td>Delete</td><td>POST</td><td>/notification/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Notification_Log</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/notification_log/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/notification_log/read_one.php?id=1</td></tr><tr><td>Create</td><td>POST</td><td>/notification_log/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/notification_log/update.php</td></tr><tr><td>Delete</td><td>POST</td><td>/notification_log/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Package_Add_Ons</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/package_add_ons/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/package_add_ons/read_one.php?id=1</td></tr><tr><td>Create</td><td>POST</td><td>/package_add_ons/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/package_add_ons/update.php</td></tr><tr><td>Delete</td><td>POST</td><td>/package_add_ons/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Package_Category</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/package_category/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/package_category/read_one.php?id=1</td></tr><tr><td>Create</td><td>POST</td><td>/package_category/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/package_category/update.php</td></tr><tr><td>Delete</td><td>POST</td><td>/package_category/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Package_Patient</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/package_patient/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/package_patient/read_one.php?id=1</td></tr><tr><td>Create</td><td>POST</td><td>/package_patient/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/package_patient/update.php</td></tr><tr><td>Delete</td><td>POST</td><td>/package_patient/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Package_Test_Groups</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/package_test_groups/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/package_test_groups/read_one.php?id=1</td></tr><tr><td>Create</td><td>POST</td><td>/package_test_groups/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/package_test_groups/update.php</td></tr><tr><td>Delete</td><td>POST</td><td>/package_test_groups/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Package_Test_Panels</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/package_test_panels/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/package_test_panels/read_one.php?id=1</td></tr><tr><td>Create</td><td>POST</td><td>/package_test_panels/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/package_test_panels/update.php</td></tr><tr><td>Delete</td><td>POST</td><td>/package_test_panels/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Patient_Bak</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/patient_bak/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/patient_bak/read_one.php?id=1</td></tr><tr><td>Create</td><td>POST</td><td>/patient_bak/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/patient_bak/update.php</td></tr><tr><td>Delete</td><td>POST</td><td>/patient_bak/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Patient_Type</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/patient_type/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/patient_type/read_one.php?id=1</td></tr><tr><td>Create</td><td>POST</td><td>/patient_type/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/patient_type/update.php</td></tr><tr><td>Delete</td><td>POST</td><td>/patient_type/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Payment</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/payment/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/payment/read_one.php?id=1</td></tr><tr><td>Create</td><td>POST</td><td>/payment/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/payment/update.php</td></tr><tr><td>Delete</td><td>POST</td><td>/payment/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Person</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/person/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/person/read_one.php?id=1</td></tr><tr><td>Create</td><td>POST</td><td>/person/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/person/update.php</td></tr><tr><td>Delete</td><td>POST</td><td>/person/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Person_Document</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/person_document/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/person_document/read_one.php?id=1</td></tr><tr><td>Create</td><td>POST</td><td>/person_document/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/person_document/update.php</td></tr><tr><td>Delete</td><td>POST</td><td>/person_document/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Person_Type</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/person_type/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/person_type/read_one.php?id=1</td></tr><tr><td>Create</td><td>POST</td><td>/person_type/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/person_type/update.php</td></tr><tr><td>Delete</td><td>POST</td><td>/person_type/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Pre_Registration</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/pre_registration/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/pre_registration/read_one.php?id=1</td></tr><tr><td>Create</td><td>POST</td><td>/pre_registration/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/pre_registration/update.php</td></tr><tr><td>Delete</td><td>POST</td><td>/pre_registration/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Ref_Message</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/ref_message/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/ref_message/read_one.php?id=1</td></tr><tr><td>Create</td><td>POST</td><td>/ref_message/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/ref_message/update.php</td></tr><tr><td>Delete</td><td>POST</td><td>/ref_message/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Ref_Payment_Method</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/ref_payment_method/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/ref_payment_method/read_one.php?id=1</td></tr><tr><td>Create</td><td>POST</td><td>/ref_payment_method/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/ref_payment_method/update.php</td></tr><tr><td>Delete</td><td>POST</td><td>/ref_payment_method/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Ref_Relationship</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/ref_relationship/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/ref_relationship/read_one.php?id=1</td></tr><tr><td>Create</td><td>POST</td><td>/ref_relationship/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/ref_relationship/update.php</td></tr><tr><td>Delete</td><td>POST</td><td>/ref_relationship/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Ref_State</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/ref_state/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/ref_state/read_one.php?id=1</td></tr><tr><td>Create</td><td>POST</td><td>/ref_state/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/ref_state/update.php</td></tr><tr><td>Delete</td><td>POST</td><td>/ref_state/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Registration</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/registration/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/registration/read_one.php?id=1</td></tr><tr><td>Create</td><td>POST</td><td>/registration/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/registration/update.php</td></tr><tr><td>Delete</td><td>POST</td><td>/registration/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Registration_Person</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/registration_person/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/registration_person/read_one.php?id=1</td></tr><tr><td>Create</td><td>POST</td><td>/registration_person/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/registration_person/update.php</td></tr><tr><td>Delete</td><td>POST</td><td>/registration_person/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Screening_Packages</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/screening_packages/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/screening_packages/read_one.php?id=1</td></tr><tr><td>Create</td><td>POST</td><td>/screening_packages/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/screening_packages/update.php</td></tr><tr><td>Delete</td><td>POST</td><td>/screening_packages/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Six_Digit_Code</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/six_digit_code/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/six_digit_code/read_one.php?id=1</td></tr><tr><td>Create</td><td>POST</td><td>/six_digit_code/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/six_digit_code/update.php</td></tr><tr><td>Delete</td><td>POST</td><td>/six_digit_code/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Sms_Log</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/sms_log/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/sms_log/read_one.php?id=1</td></tr><tr><td>Create</td><td>POST</td><td>/sms_log/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/sms_log/update.php</td></tr><tr><td>Delete</td><td>POST</td><td>/sms_log/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Sms_Notification</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/sms_notification/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/sms_notification/read_one.php?id=1</td></tr><tr><td>Create</td><td>POST</td><td>/sms_notification/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/sms_notification/update.php</td></tr><tr><td>Delete</td><td>POST</td><td>/sms_notification/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Test_Group</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/test_group/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/test_group/read_one.php?id=1</td></tr><tr><td>Create</td><td>POST</td><td>/test_group/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/test_group/update.php</td></tr><tr><td>Delete</td><td>POST</td><td>/test_group/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Test_Group_Panel</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/test_group_panel/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/test_group_panel/read_one.php?id=1</td></tr><tr><td>Create</td><td>POST</td><td>/test_group_panel/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/test_group_panel/update.php</td></tr><tr><td>Delete</td><td>POST</td><td>/test_group_panel/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Test_Location</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/test_location/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/test_location/read_one.php?id=1</td></tr><tr><td>Create</td><td>POST</td><td>/test_location/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/test_location/update.php</td></tr><tr><td>Delete</td><td>POST</td><td>/test_location/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Test_Marker</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/test_marker/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/test_marker/read_one.php?id=1</td></tr><tr><td>Create</td><td>POST</td><td>/test_marker/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/test_marker/update.php</td></tr><tr><td>Delete</td><td>POST</td><td>/test_marker/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Test_Panel</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/test_panel/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/test_panel/read_one.php?id=1</td></tr><tr><td>Create</td><td>POST</td><td>/test_panel/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/test_panel/update.php</td></tr><tr><td>Delete</td><td>POST</td><td>/test_panel/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Test_Reference_Range</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/test_reference_range/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/test_reference_range/read_one.php?id=1</td></tr><tr><td>Create</td><td>POST</td><td>/test_reference_range/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/test_reference_range/update.php</td></tr><tr><td>Delete</td><td>POST</td><td>/test_reference_range/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Test_Result</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/test_result/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/test_result/read_one.php?id=1</td></tr><tr><td>Create</td><td>POST</td><td>/test_result/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/test_result/update.php</td></tr><tr><td>Delete</td><td>POST</td><td>/test_result/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Transaction_Log</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/transaction_log/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/transaction_log/read_one.php?id=1</td></tr><tr><td>Create</td><td>POST</td><td>/transaction_log/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/transaction_log/update.php</td></tr><tr><td>Delete</td><td>POST</td><td>/transaction_log/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>User_Account</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/user_account/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/user_account/read_one.php?id=1</td></tr><tr><td>Create</td><td>POST</td><td>/user_account/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/user_account/update.php</td></tr><tr><td>Delete</td><td>POST</td><td>/user_account/delete.php</td></tr></tbody></table>

</div>
</div>

</body>
</html>
